### ISSUE TITLE
Store screenshot missing

### ISSUE THREAD

**Issue by ericaxu** [Everblush/Obsidian#3]
Seems like the screenshot image is missing. Could you please add it back? Thanks!

**Comment by mngshm** [comment]
ohh ok i'll do it

**Comment by mngshm** [comment]
done included it

**Comment by ericaxu** [comment]
You're missing a `preview.png`, search for "Everblush" here: https://github.com/obsidianmd/obsidian-releases/blob/master/community-css-themes.json

**Comment by mngshm** [comment]
https://github.com/Everblush/Obsidian/commit/b2b4a677734cf05b38bb33e573566bc602694d20?diff=split I hope this is all right to go.

**Comment by ericaxu** [comment]
Great, it's loading, thanks!

**Comment by mngshm** [comment]
Thanks to you too :D
